version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - ./environments/.env.dev
    networks:
      - webnet
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
    volumes:
      - .:/app
      - /app/node_modules
    # restart: unless-stopped

  postgres:
    image: postgres:alpine
    restart: always
    networks:
      - webnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gdong

  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
