version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - ./environments/.env.dev
    networks:
      - webnet
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
    volumes:
      - .:/app
      # - /app/node_modules
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./environments/.env.dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - webnet

  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
