version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - ./environments/.env.dev
    networks:
      - webnet
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
    volumes:
      - .:/app
      # - /app/node_modules
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./environments/.env.dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - webnet
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:5
    networks:
      - webnet

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    depends_on:
      - postgres
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
    driver: bridge
